rules:

  unpinned-uses:
    config:
      policies:
        actions/*: hash-pin
        github/codeql-action/*: hash-pin
        astral-sh/*: hash-pin

  forbidden-uses:
    config:
      allow:
        - actions/checkout
        - actions/setup-python
        - github/codeql-action/init
        - github/codeql-action/analyze
        - github/codeql-action/upload-sarif
        - astral-sh/setup-uv
